<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251212232255 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE recipe_season (recipe_id INT NOT NULL, season_id INT NOT NULL, PRIMARY KEY (recipe_id, season_id))');
        $this->addSql('CREATE INDEX IDX_7DFA458859D8A214 ON recipe_season (recipe_id)');
        $this->addSql('CREATE INDEX IDX_7DFA45884EC001D1 ON recipe_season (season_id)');
        $this->addSql('CREATE TABLE season (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE recipe_season ADD CONSTRAINT FK_7DFA458859D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE recipe_season ADD CONSTRAINT FK_7DFA45884EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE recipe_season DROP CONSTRAINT FK_7DFA458859D8A214');
        $this->addSql('ALTER TABLE recipe_season DROP CONSTRAINT FK_7DFA45884EC001D1');
        $this->addSql('DROP TABLE recipe_season');
        $this->addSql('DROP TABLE season');
    }
}
